
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gavrila Sianturi
 */
public class ExtractGUI extends javax.swing.JFrame {

    public String stegoImagePath;

    /**
     * Creates new form ExtractGUI
     */
    public ExtractGUI() {
        initComponents();
        nomorPikselLabel.setVisible(false);
        randomNumberTextField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        metodeComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        stegoImageTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lengthTextField = new javax.swing.JTextField();
        nomorPikselLabel = new javax.swing.JLabel();
        randomNumberTextField = new javax.swing.JTextField();
        prosesButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        hasilEkstraksiTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ekstraksi Pesan Rahasia");

        jLabel1.setText("Metode Ekstraksi");

        metodeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Least Significant Bit", "Pixel Indicator Technique" }));
        metodeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodeComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Stego Image");

        stegoImageTextField.setEditable(false);

        browseButton.setText("Browse");
        browseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                browseButtonMouseClicked(evt);
            }
        });
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Panjang Secret Data");

        nomorPikselLabel.setText("Nomor Piksel Awal");

        prosesButton.setText("Proses");
        prosesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prosesButtonMouseClicked(evt);
            }
        });

        jLabel5.setText("Hasil Ekstraksi");

        hasilEkstraksiTextField.setEditable(false);
        hasilEkstraksiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilEkstraksiTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(metodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(prosesButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hasilEkstraksiTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(lengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 37, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomorPikselLabel)
                                            .addComponent(randomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(stegoImageTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browseButton)))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stegoImageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomorPikselLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(randomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(prosesButton)
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasilEkstraksiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hasilEkstraksiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilEkstraksiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilEkstraksiTextFieldActionPerformed

    private void metodeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodeComboBoxActionPerformed
        // TODO add your handling code here:
        if (metodeComboBox.getSelectedIndex() == 0) {
            nomorPikselLabel.setVisible(false);
            randomNumberTextField.setVisible(false);
        } else {
            nomorPikselLabel.setVisible(true);
            randomNumberTextField.setVisible(true);
        }
    }//GEN-LAST:event_metodeComboBoxActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        randomNumberTextField.setText(null);
        JFileChooser browse = new JFileChooser();
        int returnName = browse.showOpenDialog(null);
        if (returnName == JFileChooser.APPROVE_OPTION) {
            File f = browse.getSelectedFile();
            if (f != null) {
                this.stegoImagePath = f.getAbsolutePath();
                this.stegoImageTextField.setText(stegoImagePath);
            }
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void browseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_browseButtonMouseClicked

    private void prosesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prosesButtonMouseClicked
        // TODO add your handling code here:
        if (metodeComboBox.getSelectedIndex() == 0) {
            if (stegoImageTextField.getText().isEmpty() && lengthTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih stego image dari direktori dan masukkan panjang secret data!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (stegoImageTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih stego image dari direktori!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (lengthTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Masukkan panjang secret data!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    LSBSteganography lsb = new LSBSteganography();
                    ImageProcessor img = new ImageProcessor(stegoImagePath);
                    String result = lsb.extractSecretData(img, Integer.parseInt(lengthTextField.getText()));
                    hasilEkstraksiTextField.setText(result);
                } catch (IOException ex) {
                    Logger.getLogger(ExtractGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            if (stegoImageTextField.getText().isEmpty() && lengthTextField.getText().isEmpty() && randomNumberTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih stego image dari direktori dan masukkan panjang secret data serta nomor piksel awal!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (stegoImageTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih stego image dari direktori!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (lengthTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Masukkan panjang secret data!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (randomNumberTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "masukkan nomor piksel awal!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    PITSteganography pit = new PITSteganography();
                    ImageProcessor img = new ImageProcessor(stegoImagePath);
                    int random = Integer.parseInt(randomNumberTextField.getText());
                    int secretLength = Integer.parseInt(lengthTextField.getText());
                    String result = pit.extractSecretData(img, random, secretLength);
                    hasilEkstraksiTextField.setText(result);
                } catch (IOException ex) {
                    Logger.getLogger(ExtractGUI.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_prosesButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtractGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtractGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtractGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtractGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExtractGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JTextField hasilEkstraksiTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lengthTextField;
    private javax.swing.JComboBox<String> metodeComboBox;
    private javax.swing.JLabel nomorPikselLabel;
    private javax.swing.JButton prosesButton;
    private javax.swing.JTextField randomNumberTextField;
    private javax.swing.JTextField stegoImageTextField;
    // End of variables declaration//GEN-END:variables
}
